### PR TITLE
added pr template

### PR DESCRIPTION
**Pull request by Sloth-Panda**
issue: #13 

@diyajaiswal11 

can you  please add appropriate tags to issue and pr? the tags that you have added to the issue is not correct.

### CODE REVIEW

**Comment by Sloth-Panda** [comment]
@diyajaiswal11 can you please review this pr and please add gssoc21 and level tags to both issue and pr I think the way u have taged gssoc is not gonna count so please change that

**Comment by diyajaiswal11** [comment]
> @diyajaiswal11 can you please review this pr and please add gssoc21 and level tags to both issue and pr I think the way u have taged gssoc is not gonna count so please change that

Make the following changes : 
- Please correct the spelling of issues in the first line.
- Remove the screenshots section as it may not be required in all the cases.

**Review by diyajaiswal11 — CHANGES_REQUESTED** [review]
Make the following changes :

- Please correct the spelling of issues in the first line.
- Remove the screenshots section as it may not be required in all the cases.

**Comment by Sloth-Panda** [comment]
@diyajaiswal11 I have updated it can you please add gssoc21 and a level tag to both this pr and its issue.

**Review by diyajaiswal11 — APPROVED** [review]

**Pull request merged**
