### PR TITLE
[FEATURE] added google-auth

### PR DESCRIPTION
**Pull request by Aditya201551**
## Related Issue

- Added a feature for users to login with their google account

Closes: #33 

#### Describe the changes you've made

- Added social-auth setup in `settings.py`
- Registered templates
- Added `index.html` to use login/logout feature

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

@diyajaiswal11

### CODE REVIEW

**Comment by harsh-9in** [comment]
@Aditya201551 can you plz add screenshots.

**Comment by harsh-9in** [comment]
as I am getting an error on http://127.0.0.1:8000/accounts/google/login/ this route.

**Comment by Aditya201551** [comment]
@harsh-9in I have made all the changes but I forgot that db.sqlite3 has been added to .gitignore so I will update this db file and then add it to this pr you will get the update commit within an hr and remaining all the changes done to the project will remain the same. Thank You

**Comment by Aditya201551** [comment]
@harsh-9in i have updated the branch with required changes

**Review by harsh-9in — APPROVED** [review]
Features are working fine. LGTM :+1:

**Comment by Aditya201551** [comment]
@harsh-9in  great thanks!

**Pull request merged**
